import createClient from "openapi-react-query";
import type { paths } from "../v1"; // generated by openapi-typescript
import createFetchClient from "openapi-fetch";

const fetchClient = createFetchClient<paths>({
  baseUrl: "http://localhost:8080/",
});
export const $api = createClient(fetchClient);
